### ISSUE TITLE
Provide example usages

### ISSUE THREAD

**Issue by albfan** [destin/jsf-goodies#2]
Hi, great work

I want to reuse this repo and would be cool to have examples on README.md for xslt usage and groovy script usage.

Say you want to generate xsd for another primefaces version, what would be all the steps?

**Comment by destin** [comment]
Thanks, good idea, I will try to provide such description today

**Comment by destin** [comment]
I added a few words of comment:
https://github.com/destin/jsf-goodies/blob/master/jsf_xsd/README.md

**Comment by albfan** [comment]
That's perfect
